This almost fixes the phantom hand movement issue
ovi-lab/vicon-nexus-unity-stream pull request #8
Opened 2024-07-20 02:31 UTC by omangbaheti

This fixes the rendering issue by calculating the imaginary centre of the headset. The phantom effect of hand following the headset is almost gone

2024-07-20 06:30 UTC, ahmed-shariff requested changes
This is intersting. Also, you had set the value to 1.1 something? is that meters?

2024-07-20 06:30 UTC, ahmed-shariff commented on Assets/Scripts/ViconNexusUnityStream/CustomHWDScript.cs
> +        [SerializeField] private float HMDCentreOffset;
This a better place to have this than in the project settings. Consider changing this to a Vector3, then remove the `HMDPositionOffset` and it's references across?

2024-07-20 22:22 UTC, omangbaheti commented
> This is intersting. Also, you had set the value to 1.1 something? is that meters?

So earlier with HMDPositionOffset for just applying the offset not relative to the HMD forward co-ordinates but relative to unity co-ordinate space. So it didnt really make a difference back then. Right now I am setting the values somewhere between (0,0,-100) and (0,0,-250) to get good enough results

2024-07-21 02:40 UTC, ahmed-shariff commented
Good catch! Thanx for the fix. I am still not sure why this solves that issue, which is going to keep me up at night 😅

2024-08-19 18:59 UTC, merged